apps/authentication/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_login import UserMixin

from apps import db, login_manager

from apps.authentication.util import hash_pass

class Users(db.Model, UserMixin):

    __tablename__ = 'Users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True)
    email = db.Column(db.String(64), unique=True)
    password = db.Column(db.LargeBinary)

    def __init__(self, **kwargs):
        for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
            if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
                value = value[0]

            if property == 'password':
                value = hash_pass(value)  # we need bytes here (not plain str)

            setattr(self, property, value)

    def __repr__(self):
        return str(self.username)


@login_manager.user_loader
def user_loader(id):
    return Users.query.filter_by(id=id).first()


@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = Users.query.filter_by(username=username).first()
    return user if user else None

apps/authentication/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import Email, DataRequired

# login and registration


class LoginForm(FlaskForm):
    username = StringField('Username',
                         id='username_login',
                         validators=[DataRequired()])
    password = PasswordField('Password',
                             id='pwd_login',
                             validators=[DataRequired()])


class CreateAccountForm(FlaskForm):
    username = StringField('Username',
                         id='username_create',
                         validators=[DataRequired()])
    email = StringField('Email',
                      id='email_create',
                      validators=[DataRequired(), Email()])
    password = PasswordField('Password',
                             id='pwd_create',
                             validators=[DataRequired()])

apps/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from importlib import import_module


db = SQLAlchemy()
login_manager = LoginManager()


def register_extensions(app):
    db.init_app(app)
    login_manager.init_app(app)


def register_blueprints(app):
    for module_name in ('authentication', 'home'):
        module = import_module('apps.{}.routes'.format(module_name))
        app.register_blueprint(module.blueprint)


def configure_database(app):

    @app.before_first_request
    def initialize_database():
        db.create_all()

    @app.teardown_request
    def shutdown_session(exception=None):
        db.session.remove()


def create_app(config):
    app = Flask(__name__)
    app.config.from_object(config)
    register_extensions(app)
    register_blueprints(app)
    configure_database(app)
    return app

apps/authentication/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'authentication_blueprint',
    __name__,
    url_prefix=''
)

apps/authentication/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_user,
    logout_user
)

from apps import db, login_manager
from apps.authentication import blueprint
from apps.authentication.forms import LoginForm, CreateAccountForm
from apps.authentication.models import Users

from apps.authentication.util import verify_pass

@blueprint.route('/')
def route_default():
    return redirect(url_for('authentication_blueprint.login'))

# Login & Registration

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm(request.form)
    if 'login' in request.form:

        # read form data
        username = request.form['username']
        password = request.form['password']

        # Locate user
        user = Users.query.filter_by(username=username).first()

        # Check the password
        if user and verify_pass(password, user.password):

            login_user(user)
            return redirect(url_for('authentication_blueprint.route_default'))

        # Something (user or pass) is not ok
        return render_template('accounts/login.html',
                               msg='Wrong user or password',
                               form=login_form)

    if not current_user.is_authenticated:
        return render_template('accounts/login.html',
                               form=login_form)
    return redirect(url_for('home_blueprint.index'))


@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    create_account_form = CreateAccountForm(request.form)
    if 'register' in request.form:

        username = request.form['username']
        email = request.form['email']

        # Check usename exists
        user = Users.query.filter_by(username=username).first()
        if user:
            return render_template('accounts/register.html',
                                   msg='Username already registered',
                                   success=False,
                                   form=create_account_form)

        # Check email exists
        user = Users.query.filter_by(email=email).first()
        if user:
            return render_template('accounts/register.html',
                                   msg='Email already registered',
                                   success=False,
                                   form=create_account_form)

        # else we can create the user
        user = Users(**request.form)
        db.session.add(user)
        db.session.commit()

        # Delete user from session
        logout_user()

        return render_template('accounts/register.html',
                               msg='User created successfully.',
                               success=True,
                               form=create_account_form)

    else:
        return render_template('accounts/register.html', form=create_account_form)


@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('authentication_blueprint.login')) 

# Errors

@login_manager.unauthorized_handler
def unauthorized_handler():
    return render_template('home/page-403.html'), 403


@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template('home/page-403.html'), 403


@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('home/page-404.html'), 404


@blueprint.errorhandler(500)
def internal_error(error):
    return render_template('home/page-500.html'), 500

apps/home/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'home_blueprint',
    __name__,
    url_prefix=''
)

apps/home/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from apps.home import blueprint
from flask import render_template, request
from flask_login import login_required
from jinja2 import TemplateNotFound


@blueprint.route('/index')
@login_required
def index():

    return render_template('home/index.html', segment='index')


@blueprint.route('/<template>')
@login_required
def route_template(template):

    try:

        if not template.endswith('.html'):
            template += '.html'

        # Detect the current page
        segment = get_segment(request)

        # Serve the file (if exists) from app/templates/home/FILE.html
        return render_template("home/" + template, segment=segment)

    except TemplateNotFound:
        return render_template('home/page-404.html'), 404

    except:
        return render_template('home/page-500.html'), 500


# Helper - Extract current page name from request
def get_segment(request):

    try:

        segment = request.path.split('/')[-1]

        if segment == '':
            segment = 'index'

        return segment

    except:
        return None

apps/templates/accounts/login.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="content">
        <div class="container">
            <div class="row pt-5">
                <div class="col-md-6 mt-5 offset-md-3 pt-5 mt-5">
                    <div class="card">
                        
                        <div class="card-header text-center py-4">
                            <h4 class="title">
                                Sign IN
                            </h4>

                            <h6 class="card-category">
                                {% if msg %}
                                  <span class="text-danger">{{ msg | safe }}</span>
                                {% else %}
                                <span>
                                  Add your credentials
                                </span>
                                {% endif %}  
                            </h6>
                        </div>

                        <form role="form" method="post" action="">
                                
                            {{ form.hidden_tag() }} 

                            <div class="card-body px-5 py-3"> 

                                <div class="row">
                                    <div class="col-md-12 px-md-1">
                                        <div class="form-group">
                                            <label>Username</label>
                                            {{ form.username(class="form-control") }}
                                        </div>
                                    </div>

                                    <div class="col-md-12 px-md-1">
                                        <div class="form-group">
                                            <label>Password</label>
                                            {{ form.password(class="form-control", type="password") }}
                                        </div>
                                    </div>
                                </div>

                                
                            </div>
                            
                            <div class="card-footer text-center">
                                <button type="submit" name="login" class="btn btn-fill btn-primary">Login</button>
                                
                                <br /><br />

                                <p>
                                    Don't have an account? <a href="{{ url_for('authentication_blueprint.register') }}" class="text-primary">Register</a>                            
                                </p>
                            </div>

                        </form>

                    </div>
                </div>

            </div>
        </div>

    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/accounts/register.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Register {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="content">
        <div class="container">
            <div class="row pt-5">
                <div class="col-md-6 mt-5 offset-md-3 pt-5 mt-5">
                    <div class="card">
                        <div class="card-header text-center py-4">
                            <h4 class="title">
                                Sign UP
                            </h4>

                            <h6 class="card-category">
                                {% if msg %}
                                    <span class="text-danger">{{ msg | safe }}</span>
                                {% else %}
                                    <span>
                                        Add your credentials
                                    </span>
                                {% endif %}  
                            </h6>     

                        </div>

                        {% if success %}

                            <div class="card-footer text-center">
                                <a href="{{ url_for('authentication_blueprint.login') }}" 
                                   class="btn btn-fill btn-primary">Login</a>
                            </div>

                        {% else %}

                            <form role="form" method="post" action="">
            
                                {{ form.hidden_tag() }} 

                                <div class="card-body px-5 py-3">

                                    <div class="row">
                                        <div class="col-md-12 px-md-1">
                                            <div class="form-group">
                                                <label>Username</label>
                                                {{ form.username(class="form-control") }}
                                            </div>
                                        </div>

                                        <div class="col-md-12 px-md-1">
                                            <div class="form-group">
                                                <label>Email</label>
                                                {{ form.email(class="form-control", type="email") }}
                                            </div>
                                        </div>

                                        <div class="col-md-12 px-md-1">
                                            <div class="form-group">
                                                <label>Password</label>
                                                {{ form.password(class="form-control", type="password") }}
                                            </div>
                                        </div>
                                    </div>

                                    
                                </div>
                                <div class="card-footer text-center">
                                    <button type="submit" name="register" class="btn btn-fill btn-primary">Register</button>

                                    <br /><br />
                                    
                                    <p>
                                        Have an account? <a href="{{ url_for('authentication_blueprint.login') }}" class="text-primary">Login</a>
                                    </p> 
                                </div>
                            
                            </form>

                        {% endif %} 

                    </div>
                </div>

            </div>
        </div>

    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/login.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="content">
        <div class="container">
            <div class="row pt-5">
                <div class="col-md-6 mt-5 offset-md-3 pt-5 mt-5">
                    <div class="card">
                        <div class="card-header text-center py-4">
                            <h4 class="title">Login to CT ADMIN</h4>
                        </div>
                        <div class="card-body px-5 py-3">
                            <form>
                                <div class="row">
                                    <div class="col-md-12 px-md-1">
                                        <div class="form-group">
                                            <label>Username</label>
                                            <input type="text" class="form-control" placeholder="Username"
                                                    value="michael23">
                                        </div>
                                    </div>

                                    <div class="col-md-12 px-md-1">
                                        <div class="form-group">
                                            <label>Password</label>
                                            <input type="password" class="form-control" placeholder="password"
                                                    value="example@gmail.com">
                                        </div>
                                    </div>
                                </div>

                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-fill btn-primary">Login</button>
                            
                            <br /><br />

                            <p>
                                Don't have an account? <a href="/register.html" class="text-primary">Register</a>                            
                            </p>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/map.html
{% extends "layouts/base.html" %}

{% block title %} Maps {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="content">
    <div class="row">
      <div class="col-md-12">
        <div class="card card-plain">
          <div class="card-header">
            Google Maps
          </div>
          <div class="card-body">
            <div id="map" class="map"></div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <script>
    $(document).ready(function() {
      // Javascript method's body can be found in assets/js/demos.js
      demo.initGoogleMaps();
    });
  </script>

{% endblock javascripts %}

apps/templates/home/page-403.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Error 403 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="content">
        <div class="container">
            <div class="row pt-5">
                <div class="col-md-6 mt-5 offset-md-3 pt-5 mt-5">
                    <div class="card">
                        <div class="card-header text-center py-4">
                            <h3 class="title">
                                Error 403
                            </h3>
                        </div>
                        <div class="card-body px-2 py-2">

                            <p class="text-center">
                                Access denied - Please contact support.
                            </p>

                        </div>
                        <div class="card-footer text-center">
                            <a href="/" class="btn btn-fill btn-primary">HOME</a>
                            
                            <br /><br />

                            <p>
                                Get <a href="#" class="text-primary">Support</a>                            
                            </p>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/page-404.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Error 404 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="content">
        <div class="container">
            <div class="row pt-5">
                <div class="col-md-6 mt-5 offset-md-3 pt-5 mt-5">
                    <div class="card">
                        <div class="card-header text-center py-4">
                            <h3 class="title">
                                Error 404
                            </h3>
                        </div>
                        <div class="card-body px-2 py-2">

                            <p class="text-center">
                                Page not found - Please contact support.
                            </p>

                        </div>
                        <div class="card-footer text-center">
                            <a href="/" class="btn btn-fill btn-primary">HOME</a>
                            
                            <br /><br />

                            <p>
                                Get <a href="#" class="text-primary">Support</a>                            
                            </p>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/includes/footer-fullscreen.html
<footer class="footer px-5 py-4 fixed-bottom">
    <div class="copyright mx-auto float-none text-center">
        
        &copy; <a target="_blank" href="https://bit.ly/3fKQZaL">Creative Tim</a> - coded by AppSeed.

    </div>
</footer>

apps/templates/includes/footer.html
<footer class="footer">
    <div class="container-fluid">
        <ul class="nav">
            <li class="nav-item">
                <a target="_blank" href="https://appseed.us/product/black-dashboard/" class="nav-link">
                    Download
                </a>
            </li>
            <li class="nav-item">
                <a target="_blank" href="https://appseed.us/support/" class="nav-link">
                    Support
                </a>
            </li>
        </ul>
        <div class="copyright">
            &copy; <a target="_blank" href="https://bit.ly/3fKQZaL">Creative Tim</a> - coded by AppSeed.
        </div>
    </div>
</footer>

apps/templates/includes/navigation.html
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent">
            <div class="container-fluid">
                <div class="navbar-wrapper">
                    <div class="navbar-toggle d-inline">
                        <button type="button" class="navbar-toggler">
                            <span class="navbar-toggler-bar bar1"></span>
                            <span class="navbar-toggler-bar bar2"></span>
                            <span class="navbar-toggler-bar bar3"></span>
                        </button>
                    </div>
                    <a class="navbar-brand" href="javascript:void(0)">Dashboard</a>
                </div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                </button>
                <div class="collapse navbar-collapse" id="navigation">
                    <ul class="navbar-nav ml-auto">
                        <li class="input-group d-flex align-items-center mb-0">
                            <label class="switch theme-switch">
                                <input type="checkbox" class="bsc" checked="">
                                <span class="slider"></span>
                            </label>
                        </li>
                        <li class="search-bar input-group">
                            <button class="btn btn-link" id="search-button" data-toggle="modal"
                                    data-target="#searchModal"><i class="tim-icons icon-zoom-split"></i>
                                <span class="d-lg-none d-md-block">Search</span>
                            </button>
                        </li>
                        <li class="dropdown nav-item">
                            <a href="javascript:void(0)" class="dropdown-toggle nav-link" data-toggle="dropdown">
                                <div class="notification d-none d-lg-block d-xl-block"></div>
                                <i class="tim-icons icon-sound-wave"></i>
                                <p class="d-lg-none">
                                    Notifications
                                </p>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-right dropdown-navbar">
                                <li class="nav-link"><a href="#" class="nav-item dropdown-item">Mike John responded to
                                    your email</a></li>
                                <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">You
                                    have 5 more tasks</a></li>
                                <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Your
                                    friend Michael is in town</a></li>
                                <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Another
                                    notification</a></li>
                                <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Another
                                    one</a></li>
                            </ul>
                        </li>
                        <li class="dropdown nav-item">
                            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                                <div class="photo">
                                    <img src="{{ config.ASSETS_ROOT }}/img/anime3.png" alt="Profile Photo">
                                </div>
                                <b class="caret d-none d-lg-block d-xl-block"></b>
                                <p class="d-lg-none">
                                    Log out
                                </p>
                            </a>
                            <ul class="dropdown-menu dropdown-navbar">
                                <li class="nav-link">
                                    <a href="/user.html" class="nav-item dropdown-item">Profile</a>
                                </li>
                                <li class="dropdown-divider"></li>
                                <li class="nav-link">
                                    <a href="{{ url_for('authentication_blueprint.logout') }}" 
                                       class="nav-item dropdown-item">Logout</a>
                                </li>
                            </ul>
                        </li>
                        <li class="separator d-lg-none"></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="modal modal-search fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModal"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="SEARCH">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <i class="tim-icons icon-simple-remove"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Navbar -->
        

apps/templates/includes/sidebar.html
    <div class="sidebar">
        <!--
          Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red"
      -->
        <div class="sidebar-wrapper">
            <div class="logo">
                <a href="javascript:void(0)" class="simple-text logo-mini">
                    CT
                </a>
                <a href="javascript:void(0)" class="simple-text logo-normal">
                    Creative Tim
                </a>
            </div>
            <ul class="nav">
                <li class="{% if 'index' in segment %} active {% endif %} ">
                    <a href="/">
                        <i class="tim-icons icon-chart-pie-36"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                <li class="{% if 'icons' in segment %} active {% endif %}">
                    <a href="/icons.html">
                        <i class="tim-icons icon-atom"></i>
                        <p>Icons</p>
                    </a>
                </li>
                <li class="{% if 'map' in segment %} active {% endif %}">
                    <a href="/map.html">
                        <i class="tim-icons icon-pin"></i>
                        <p>Maps</p>
                    </a>
                </li>
                <li class="{% if 'notifications' in segment %} active {% endif %}">
                    <a href="/notifications.html">
                        <i class="tim-icons icon-bell-55"></i>
                        <p>Notifications</p>
                    </a>
                </li>
                <li class="{% if 'user' in segment %} active {% endif %}">
                    <a href="/user.html">
                        <i class="tim-icons icon-single-02"></i>
                        <p>User Profile</p>
                    </a>
                </li>
                <li class="{% if 'tables' in segment %} active {% endif %}">
                    <a href="/tables.html">
                        <i class="tim-icons icon-puzzle-10"></i>
                        <p>Table List</p>
                    </a>
                </li>
                <li class="{% if 'typography' in segment %} active {% endif %}">
                    <a href="/typography.html">
                        <i class="tim-icons icon-align-center"></i>
                        <p>Typography</p>
                    </a>
                </li>
                <li>
                    <a href="/rtl.html">
                        <i class="tim-icons icon-world"></i>
                        <p>RTL Support</p>
                    </a>
                </li>
                <li>
                    <a href="{{ url_for('authentication_blueprint.logout') }}">
                        <i class="tim-icons icon-button-power"></i>
                        <p>Logout</p>
                    </a>
                </li>
            </ul>
        </div>
    </div>